Ajout des dates de début et de fin
TableauBits/Yatga pull request #109
Opened 2023-02-26 20:55 UTC by hvdbm

## Description

### :rocket: Nouveauté
* Ajout d'une option de date de fin de la constitution.
* Enregistrement de la date de début.

### :tada: Quality of life
* Révision de l'interface de la page d'accueil.

### :hammer_and_wrench: Refactoring
* Mise à jours des packages.
* Retrait des options non utilisées pour les niveaux d'anonymats d'une constitution. 

## Dépendance issues/pull request

* Close #104

## Checklist

- [ ] Titre
- [ ] Label
- [ ] Catégorie

2023-02-28 17:34 UTC, Ithyx requested changes

2023-02-28 17:34 UTC, Ithyx commented on package.json
> +    "chelys": "^2.10.0",
faut matcher la version avec Kalimba (2.11.0 au lieu de 2.10)

2023-02-28 17:34 UTC, Ithyx commented on src/app/components/admin-page/new-constitution/new-constitution.component.ts
>  		const invalidValues = this.checkFormValidity();
Besoin de mettre à jour `checkFormValidity` pour vérifier la date de fin

2023-06-30 20:05 UTC, Ithyx approved these changes
Une petite suggestion pour l'affichage, mais libre à toi de l'accepter ou pas, tu peux merge quand t uveux

2023-06-30 20:05 UTC, Ithyx commented on src/app/components/constitution-page/constitution.component.html
> +	<span> {{getRemainingTimeMsg()}} </span>
Je verrais bien une ligne en plus pour séparer un peu
```suggestion
    <br>
	<span> {{getRemainingTimeMsg()}} </span>
```

2023-07-01 19:12 UTC, hvdbm commented on src/app/components/constitution-page/constitution.component.html
> +	<span> {{getRemainingTimeMsg()}} </span>
Un <br> est peut-être trop, j'ai proposé un entre deux

2023-07-01 19:16 UTC, merged