Enlveé l'étirement des images de profil
TableauBits/Yatga pull request #110
Opened 2023-03-23 16:22 UTC by rakruk

## Description
J'ai modifié le CSS pour que les images des utilisateurs ne soient plus étirées. Les pixels ont maintenant un ratio de 1:1, ce qui devrait améliorer l'apparence des images.

### :tada: Quality of life

- Les images des utilisateurs ne sont plus étirées.

## Checklist

- [x] Titre
- [ ] Label
- [ ] Catégorie

2023-03-23 17:28 UTC, Ithyx submitted a review, later dismissed
LGTM

2023-03-23 17:34 UTC, hvdbm requested changes
Je suis pas d'accord avec cette approche. En donnant une taille adaptative on retire l'alignement des images ce qui fait un drôle d'effet dans la page des utilisateurs. On peut le voir ici où les pseudos des utilisateurs ne sont plus à la même hauteur à cause de l'image de profile :
<img width="736" alt="Capture d’écran, le 2023-03-23 à 13 33 20" src="https://user-images.githubusercontent.com/43498878/227290339-8f13e0bf-f0d8-486f-9e34-09c626167e0b.png">

2023-03-23 18:24 UTC, rakruk commented
Je peux essayer de faire ça mais je préfère entièrement des images non
étirées dans des cases flexibles plutôt que des images étirées dans des
cases rigides. Si tu penses que c'est une régression tu peux close la PR

On Thu, Mar 23, 2023, 13:34 Hugo VDBM ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Je suis pas d'accord avec cette approche. En donnant une taille adaptative
> on retire l'alignement des images ce qui fait un drôle d'effet dans la page
> [image: Capture d’écran, le 2023-03-23 à 13 33 20]
> <https://user-images.githubusercontent.com/43498878/227290339-8f13e0bf-f0d8-486f-9e34-09c626167e0b.png>
> de profil.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TableauBits/Yatga/pull/110#pullrequestreview-1355166608>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKI7JWJQUTIF545WAFBMKG3W5SCSTANCNFSM6AAAAAAWFN2YJM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-03-23 21:09 UTC, rakruk commented
Le dernier commit devrait résoudre le problème que tu avais @hvdbm

2023-03-31 16:33 UTC, hvdbm reviewed
C'est mieux niveau alignement mais il y a quand même un détail qui me perturbe : désormais la hauteur d'une carte utilisateur va prendre la plus grande hauteur de sa ligne. Ça veut dire que 2 rangées d'utilisateurs peuvent avoir des hauteurs différentes (on peut bien voir la différence entre le staff et les membres)

2023-03-31 16:33 UTC, hvdbm commented on src/app/components/admin-page/manage-roles/manage-roles.component.html
> -      <td> <img class="picture3 avatar" [src]="user.photoURL" matTooltip="{{user.displayName}}"> </td>
Pourquoi on fait ce changement ? Cette page ne redimensionne pas les images d'utilisateurs et n'est disponible que pour les admins.

2023-06-27 15:54 UTC, hvdbm commented
Pris en compte dans #112

2023-06-27 15:54 UTC, closed without merging