Feature/recolor
TableauBits/Yatga pull request #112
Opened 2023-04-13 20:28 UTC by Aezurly

## Description

Recolor entier du site, amélioration mise en page et gestion des espaces, ergonomie, refonte de la navbar

### :rocket: Nouveauté

* Nouvelle palette de couleur 🎨 
* Refonte de la page d'accueil 📄 
* Refonte de la navbar (avant était prise d'une template) 🟪 
* Amélioration de l'ergonomie globale du site 🛰️ 

## 🎨 Amélioration graphique

### Page d'accueil :
#### Fenêtre étroite :
Avant :

![avant etroit](https://user-images.githubusercontent.com/66571923/231873417-d0530516-386b-4bc3-84ef-dc05926f5749.png)

Après :

![après etroit](https://user-images.githubusercontent.com/66571923/231873974-6e5ecd6c-ba76-4794-a2d6-bbb1a454878b.png)

#### Fenêtre Large

Avant :

![avant large](https://user-images.githubusercontent.com/66571923/231874220-ff7d9f5b-f056-4a71-8744-8a0baa057d6c.png)

Après :

![après large](https://user-images.githubusercontent.com/66571923/231874308-41a78859-1aee-4a80-99a6-9a1c5fcbc301.png)

### Autres pages :

Aucun changement autre que la palette de couleur car l'accès de prévisualisation local empêche la vue des pages qui demandent une connexion.

## Modifications encore à venir :

- [ ] Adaptation complète pour mobile
- [ ] Vérification des modifications pour un utilisateur connecté _(impossible de tester la connexion lorsque le preview est local)_ 
- [ ] Refonte graphique des pages des constitutions et adaptations sur mobile

2023-04-13 21:32 UTC, Ithyx commented
Bonjour @Aezurly, merci pour ta PR! Comme je suis principalement responsable du backend, je ne me permettrais pas de donner mon avis sur le UI, ça sera surtout à voir avec @hvdbm dès qu'il aura du temps. Cependant, ce que tu as mentionné ici n'est pas tout à fait vrai, et je voudrais te donner un petit conseil:
> Aucun changement autre que la palette de couleur car l'accès de prévisualisation local empêche la vue des pages qui demandent une connexion.

Il y a bel et bien un moyen assez simple de se connecter sur son client local. De base, lorsque tu fais `ng serve` pour lancer Yatga localement, l'environnement de debug est utilisé, ce qui signifie que Yatga va essayer de cherche une instance de Kalimba (le serveur) qui serait également hosté localement. Cependant, en utilisant la commande `ng serve --configuration production`, ton instance locale de Yatga se connectera au serveur déployé sur fly.io (AKA le serveur utilisé normalement lorsqu'on accès à Yatga depuis `matdactivity.web.app`.

J'ai regardé un peu ce que ça donnait, et certaines pages, notamment celles des utilisateurs et les liste de chansons (avec la vue "carte") dans les constitutions sont non fonctionnelles en ce moment, attends toi donc à ce que @hvdbm refuse tes changements tant que ça ne sera pas fixé.

En tout cas, bravo pour cette première PR, et merci encore, toutes les contributions sont appréciées :partying_face:

2023-04-14 00:26 UTC, hvdbm commented
Comme @Ithyx l'a mentionné c'est surtout moi qui gère ce repo mais n'étant pas un spécialiste dans l'aspect visuel ce genre de PR est le bienvenue. Je pourrais faire un tour des changements d'ici 2-3 semaines mais il semblerait que @Ithyx a déjà relevé quelques trucs intéressants.

Également :
> Modifications encore à venir :
 Adaptation complète pour mobile
 Vérification des modifications pour un utilisateur connecté (impossible de tester la connexion lorsque le preview est local)
 Refonte graphique des pages des constitutions et adaptations sur mobile 

Je vois que tu veux aussi adapter l'apparence du site au format mobile mais je pense que ça serait mieux de le garder pour une seconde PR afin de ne pas trop surcharger celle-ci qui à l'air de plus se concentrer sur la palette de couleur.

2023-04-18 15:40 UTC, Aezurly commented
Alors déjà merci pour la réponse rapide. Il y a encore pas mal de trucs que je comprends pas tout à fait, je découvre angular donc bon. 

Merci pour le tip pour ng serve --configuration production, et en effet j'ai pu voir que j'avais accidentellement brisé pas mal de trucs sur certaines pages. Je vais réparer tout ça prochainement, j'ai juste supprimé un truc qui était visiblement important mais je peux le récupérer facilement.

Et pour mobile en effet, je vais me concentrer sur le recolor pour l'instant et je verrais après pour mobile, même si j'ai déjà avancé quelques trucs, mais il y a beaucoup à faire pour les pages des constitutions.

2023-05-14 23:39 UTC, Aezurly commented
Après un petit mois et une période d'examens finaux passée, tout a l'air de correctement fonctionner de ce que j'ai pu vérifié, et j'espère que mes modifications pourront être adoptées pour la prochaine Xénocratie.
S'il y a n'importe quel soucis ou question par rapport à mon code n'hésitez pas, mais je pense l'avoir fait suffisamment compréhensible.

J'attends donc votre review @hvdbm @Ithyx, si possible avant vos vacances.

2023-05-23 03:51 UTC, hvdbm requested changes
De manière plus général, les barres de séparations sont devenues violettes mais certaines sont restés grises :
- Page de profile d'un utilisateur 
- Page d'une constitution : sous-page d'export, soirée électorale, navigateur de chanson, navigateur de chansons aléatoire, navigateur de votes dans zone électorale, etc...

Également ces nouvelles barres semblent un peu fines et sont parfois difficile à voir avec le fond noir, il serait peut-être intéressant d'essayer de les élargir.

Un autre cas qu'on a repéré est un problème au niveau du bouton `Télécharger les résultats` dans la sous-section `Mon Profil` dans la section `Résultats` :
<img width="1272" alt="Capture d’écran, le 2023-05-22 à 23 30 34" src="https://github.com/TableauBits/Yatga/assets/43498878/acce3504-4e04-40a9-bf05-c44f92f04e7d">

Mais le reste est nickel, merci pour la nouvelle palette de couleurs 👍

2023-05-23 03:51 UTC, hvdbm commented on src/app/components/home-page/home-page.component.scss
> +  margin-top: min(5%, 100px);
Le titre est peut-être un peu trop grand
```suggestion
  font-size: 7vw;
  line-height: 100%;
  margin-top: min(5%, 100px);
```

2023-05-23 03:51 UTC, hvdbm commented on src/app/components/home-page/home-page.component.scss
> +}
L'espace entre le sous-titre et la barre de séparation est trop grande pour de grands écrans.
```suggestion
.title {
  margin-bottom: 4vw;
}
```

2023-05-23 03:51 UTC, hvdbm commented on src/app/components/navbar/navbar.component.scss
> +  font-size: 35px;
```suggestion
  font-size: 25px;
```

2023-05-23 03:51 UTC, hvdbm commented on src/app/components/navbar/navbar.component.html
> +			<button mat-raised-button class="btn btn-primary purple navbar-button" [matMenuTriggerFor]="menu">
Il faut garder l'aspect dropdown button pour savoir que ce bouton est une liste
```suggestion
			<button mat-raised-button class="btn btn-primary dropdown-toggle purple navbar-button" [matMenuTriggerFor]="menu">
```

2023-05-23 03:51 UTC, hvdbm commented on src/app/components/users-page/users-page.component.html
> +		</defs><g id="Layer_2" data-name="Layer 2">
Les balises `defs` ne sont pas utilisées.
```suggestion
		<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 501.23 20.1"><g id="Layer_2" data-name="Layer 2">
```

2023-05-23 03:51 UTC, hvdbm commented on src/app/components/users-page/users-page.component.html
> +			</defs><g id="Layer_2" data-name="Layer 2">
```suggestion
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 501.23 20.1"><g id="Layer_2" data-name="Layer 2">
```

2023-05-23 03:51 UTC, hvdbm commented on src/app/components/users-page/users-page.component.html
> +			</defs><g id="Layer_2" data-name="Layer 2">
```suggestion
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 501.23 20.1"><g id="Layer_2" data-name="Layer 2">
```

2023-05-23 03:51 UTC, hvdbm commented on src/app/components/users-page/users-page.component.html
> +		<h2 class="user-title">Équipe Technique
Proposition pour uniformiser les titres de sections. Également, est-ce que c'est normal qu'il y a un espace plus important entre les deux mots ?
```suggestion
		<h2 class="user-title">Équipe Matbay
```

2023-05-23 03:51 UTC, hvdbm commented on src/app/components/users-page/users-page.component.html
> +		<h2 class="user-title">Matbay Subjects
```suggestion
		<h2 class="user-title">Cobayes Matbay
```

2023-05-23 03:51 UTC, hvdbm commented on src/app/components/users-page/users-page.component.scss
> +	// margin-bottom: 10px;
On peut retirer ces commentaires :)
```suggestion
```

2023-05-23 03:51 UTC, hvdbm commented on src/app/components/users-page/users-page.component.scss
> +	// border-top: 2px solid $admin;
```suggestion
```

2023-05-23 03:51 UTC, hvdbm commented on src/app/components/constitution-page/constitution.component.html
>  	</button>
Le fait qu'un bouton soit disabled est moins clair. Il faudrait avoir quelque chose avec l'aspect "grisé", comme sur l'ancienne palette de couleur :
<img width="227" alt="Capture d’écran, le 2023-05-22 à 23 26 59" src="https://github.com/TableauBits/Yatga/assets/43498878/d7efac65-6b37-47da-91e4-6b01105364fc">
<img width="194" alt="Capture d’écran, le 2023-05-22 à 23 27 17" src="https://github.com/TableauBits/Yatga/assets/43498878/005b633f-406c-485e-8fd4-c7ce7a6bdf3b">

2023-05-23 03:51 UTC, hvdbm commented on src/app/components/constitution-page/constitution.component.html
>  </mat-sidenav-container>
Même commentaire sur l'aspect "grisé" lorsque disabled.

2023-07-11 05:41 UTC, Aezurly commented
> De manière plus général, les barres de séparations sont devenues violettes mais certaines sont restés grises :
> 
> * Page de profile d'un utilisateur
> * Page d'une constitution : sous-page d'export, soirée électorale, navigateur de chanson, navigateur de chansons aléatoire, navigateur de votes dans zone électorale, etc...
> 
> Également ces nouvelles barres semblent un peu fines et sont parfois difficile à voir avec le fond noir, il serait peut-être intéressant d'essayer de les élargir.
> 
> Un autre cas qu'on a repéré est un problème au niveau du bouton `Télécharger les résultats` dans la sous-section `Mon Profil` dans la section `Résultats` : <img alt="Capture d’écran, le 2023-05-22 à 23 30 34" width="1272" src="https://user-images.githubusercontent.com/43498878/240118164-acce3504-4e04-40a9-bf05-c44f92f04e7d.png">
> 
> Mais le reste est nickel, merci pour la nouvelle palette de couleurs 👍

- On m'a aussi fait la remarque sur la faible visibilité `hr` mais moi j'aimais bien haha, mais bon puisque c'est l'avis de plusieurs personne j'ai modifié ça. Par contre je trouve que 2px c'est trop, donc j'ai juste augmenté l'opacité. Si tu préfères augmenter l'épaisseur tu peux toujours mais moi j'aime pas. Ensuite j'avais en effet manqué certains `custom-br` (ancienne barres grises) sur certaines pages, notamment pas mal où je n'ai pas accès (administrateur, création de constitution etc...) du coup j'ai en effet remplacé tous les `custom br` en `hr` maintenant, mais je n'ai pas pu vérifier la bonne intégration de toutes.

- Pour le problème du bouton de `Télécharger les résultats` dans la sous-section `Mon Profil` dans la section `Résultats`, pareil, moi je le voyais pas, probablement parce que je suis pas admin.
![image](https://github.com/TableauBits/Yatga/assets/66571923/d8122936-a56a-4907-b0d0-3015a983aa83)Mais bon j'ai tout de même fait de mon mieux avec ton screen pour régler la situation même sans prévisualisation de mes modifications.

> Le fait qu'un bouton soit disabled est moins clair. Il faudrait avoir quelque chose avec l'aspect "grisé", comme sur l'ancienne palette de couleur : <img alt="Capture d’écran, le 2023-05-22 à 23 26 59" width="227" src="https://user-images.githubusercontent.com/43498878/240117805-d7efac65-6b37-47da-91e4-6b01105364fc.png"> <img alt="Capture d’écran, le 2023-05-22 à 23 27 17" width="194" src="https://user-images.githubusercontent.com/43498878/240117813-005b633f-406c-485e-8fd4-c7ce7a6bdf3b.png">

- J'avais repéré le même problème mais puisque ces boutons sont des templates d'Angular j'avais pas réussi à changer la couleur de fond puis j'avais oublié ce problème 🤔 mais en passant plus de temps j'ai trouvé une solution normalement, même si j'ai peur d'avoir cassé le changement disabled/active button mais bon normalement ça devrait fonctionner. J'ai improvisé un style mais c'est modifiable avec la combinaison ci-dessous
![image](https://github.com/TableauBits/Yatga/assets/66571923/93c494a7-2d96-432b-8dd7-238bc837e876)
```scss
.sidenav .mat-button-disabled {
  background-color: #222;
  color: #b7b7b7;
  font-weight: 400;
  opacity: 0.6;
}
``` 

- Pour le reste des modifications même si esthétiquement sur certain trucs je suis pas forcément d'accord (j'aime les gros titres :eyes: ), c'est une question de goûts et de couleurs donc je te les laisse.

2023-07-11 05:56 UTC, Aezurly commented on src/app/components/users-page/users-page.component.html
> +		<h2 class="user-title">Équipe Technique
Alors oui c'est normal mais pour être honnête je ne me rappelle plus de pourquoi j'avais fait cette modification, je crois que c'était par rapport à l'svg qui devait avoir une certaine largeur ou quelque chose comme ça, mais on peut toujours supprimer `word-spacing: 15px;` dans `src/app/components/users-page/users-page.component.scss
`
```scss
.user-title{
    margin: auto auto 10px;
    text-align: center;
    font-size: 30px;
    font-weight: 100;
    / word-spacing: 15px;
    width: max-content;
}
```

2023-08-06 23:10 UTC, hvdbm approved these changes

2023-08-07 01:13 UTC, hvdbm approved these changes

2023-08-07 01:40 UTC, Ithyx approved these changes

2023-08-07 21:59 UTC, merged