Refactorisé et modifié la logique de tri des chansons
TableauBits/Yatga pull request #86
Opened 2022-09-30 19:50 UTC by rakruk

### :bug: Bugfix

Refactorisé et modifié la logique de tri des chansons.

## Checklist

- [ ] Titre
- [ ] Label
- [ ] Catégorie

2022-10-12 23:33 UTC, hvdbm requested changes
On peut commencer avec ça. Aussi, il y d'autres compares dans le code qui peuvent être remplacé (ex: `compareUserScore`, `compareConstitutionASC`, `compareSongFavoriteStat`, etc)

2022-10-12 23:33 UTC, hvdbm commented on sonar-project.properties
> +sonar.sourceEncoding=UTF-8
Est-ce qu'on a vraiment besoin de ce fichier ou il faut l'ajouter dans le .gitignore ?

2022-10-12 23:33 UTC, hvdbm commented on src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.ts
> +    return Array.from(this.songs.values())
Pourquoi avoir retiré le sort décroissant sur les chansons ?

2022-10-12 23:33 UTC, hvdbm commented on src/app/types/song.ts
> + */
Le plus beau commentaire du repo

2022-10-12 23:33 UTC, hvdbm commented on src/app/components/constitution-page/song-list/song-list.component.ts
> +		songs.sort(compareObjectsFactory("title", this.cardsSortASC));
Pourquoi on sort par "title" ici ? Ça devrait être "id" non ?

2022-10-12 23:33 UTC, hvdbm commented on src/app/components/constitution-page/song-list/song-list.component.ts
> +		let songs = Array.from(this.songs.values())
```suggestion
		let songs = Array.from(this.songs.values());
```

2022-10-12 23:33 UTC, hvdbm commented on src/app/components/constitution-page/votes/votes-grade/votes-grade.component.ts
> +		let songsToVote = Array.from(this.songs.values())
```suggestion
		let songsToVote = Array.from(this.songs.values());
```

2022-10-12 23:33 UTC, hvdbm commented on src/app/components/constitution-page/votes/votes-grade/votes-grade.component.ts
> +		songsToVote.sort(compareObjectsFactory("title", this.cardsSortASC));
Pourquoi sort par "title" ? Pour avoir l'ordre chronologie, il faut que ce soit sort par id.
```suggestion
		songsToVote.sort(compareObjectsFactory("id", this.cardsSortASC));
```

2022-10-12 23:33 UTC, hvdbm commented on src/app/components/constitution-page/export/export.component.ts
> +    const songs = Array.from(this.songs.values()).sort(compareObjectsFactory("title", false))
Pourquoi sort par "title" ? Pour avoir l'ordre chronologie, il faut que ce soit sort par id.
```suggestion
		const songs = Array.from(this.songs.values()).sort(compareObjectsFactory("id", false));
```

2022-10-12 23:33 UTC, hvdbm commented on src/app/components/constitution-page/song-list/song-list.component.ts
> +			songs = songs.sort(compareObjectsFactory<Song>((s: Song) => this.isAFavorite(s), false));
Quand je teste en local, les favoris sont à la fin de la page, il faudrait probablement inverser.

2022-10-12 23:33 UTC, hvdbm commented on src/app/components/constitution-page/votes/votes-grade/votes-grade.component.ts
> +			songsToVote = songsToVote.sort(compareObjectsFactory<Song>((s: Song) => this.isAFavorite(s), false));
Je ne sais pas trop où est l'erreur mais quand j'exécute en local, il n'y aucune chanson qui s'affiche.

2022-11-27 20:41 UTC, rakruk commented
C'est toujours en attente de quelqu'un pour review :)

2022-11-27 21:39 UTC, hvdbm submitted a review, later dismissed
J'approuve pour que tu puisses merge de ton côté, mais juste fix les petits commentaires avant 👍

2022-11-27 21:39 UTC, hvdbm commented on src/app/types/song.ts
> +}
Finalement il faudrait peut-être déplacer cette fonction de fichier, le fichier `song.ts` n'a pas de trop de sens ici. `utils.ts` semble plus approprié.

2022-11-27 21:39 UTC, hvdbm commented on src/app/components/constitution-page/song-list/song-list.component.ts
> +		let songs = Array.from(this.songs.values())
;

2022-11-27 21:39 UTC, hvdbm commented on src/app/components/constitution-page/export/export.component.ts
> +    const songs = Array.from(this.songs.values()).sort(compareObjectsFactory("id", false))
```suggestion
    const songs = Array.from(this.songs.values()).sort(compareObjectsFactory("id", false));
```

2022-11-27 23:37 UTC, rakruk commented on .vscode/launch.json
> +    ]
C'est le fichier qui indique la task de débogage. Essaye toi-même d'appuyer sur F5 et ca te lance chrome avec la page d'ouverte, en plus tu peux mettre des breakpoint dans le typescript vscode et ca va break sur chrome. On n'arrête pas le progrès. Fonctionnait à merveille pour projet 2, malheureusement ici google refuse sensiblement l'authentification quand chrome est lancé en mode debug, donc aucun moyen de se login sur matb en mode chrome debug. Dommage!

2022-11-27 23:40 UTC, rakruk commented on src/app/components/constitution-page/export/export.component.ts
> +    const songs = Array.from(this.songs.values()).sort(compareObjectsFactory("id", false))
#92

2022-11-28 04:07 UTC, hvdbm approved these changes

2022-11-28 15:59 UTC, merged